### PR TITLE
Table.OnMouseMove: Avoided NullReferenceException

### PR DESCRIPTION
**Pull request by schoetbi**
#33

### CODE REVIEW

**Review by jeoffman — APPROVED** [review]
Careful, that column is HOT!

**Review by schalpat — APPROVED** [review]
ok, pick the last commit

**Comment by schoetbi** [comment]
@schalpat in 8d3d527 Table.cs:7479 the methode RaiseHeaderMouseLeave is called twice. I will merge your commit into c45a992 and fix it.

**Comment by schoetbi** [comment]
Merged with 783252

**Pull request closed without merging**
