### PR TITLE
NumberCellRenderer: No Strikethrough

### PR DESCRIPTION
**Pull request by schoetbi**
Test hinzugefügt
added packages to .gitignore

### CODE REVIEW

**Comment by jeoffman** [comment]
The code seems fine - a little cleaner and easier to read than the original.

Was there something wrong with the numeric cell showing strikeout fonts for invalid numbers? It seemed like an OK feature to me - I am not sure why you want to remove it. A bug?

Maybe you are trying to allow text in some numeric cells? Is this similar to a change over in my fork where I added a custom cell editor? That code allowed you to set the cell editor (and thus renderer) for this kind of thing. I am talking about my commit from 10/29/2015 that I called "Ver 1.5.0" here: https://github.com/jeoffman/XPTable/commit/51461c7798ed524e9d5b6bbbe345c7ac73e4b59e
Is that another approach to this problem? Or maybe I completely missed the purpose of removing the font?

**Comment by schoetbi** [comment]
The strikeout font comes when decimal.Tryparse returns false. But since the range of the decimal type and the double or the float types is smaller the strikeout font also appears when valid double or float numbers are printed. 

See here:
https://msdn.microsoft.com/de-de/library/system.single.maxvalue(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.decimal.maxvalue.aspx
https://msdn.microsoft.com/de-de/library/system.double.maxvalue(v=vs.110).aspx

I think, that the strikeout behaviour should really be bussines logic above xptable and not integrated, because maybe some client applications want to express other things with strikeout font.

Your solution with the custom renderer gives the customer app a better method to implement those requirements.

Here a python script to verify this:

```
maxfloat = 3.402823e38
maxdouble = 1.7976931348623157E+308
maxdec = 79228162514264337593543950335

-- Gives True
maxfloat > maxdec

-- Also true
maxdouble > maxdec
```

**Comment by jeoffman** [comment]
Another quick-ish fix could be to add a public setter to strikeoutFont (something like "ErrorFont") and let the user change the font if needed.

**Comment by schoetbi** [comment]
You could assign the Font for each cell separatelly. This way the application itself is under full control. As it should be.

I think modifying the font on a renderer is rarely used since all cells will have this font. More likeley an application wants to modify one cell only.

```
var row = new Row(new[]
    {
        new Cell("good"),
        new Cell("Error")
        {
            Font = new Font(FontFamily.GenericSerif, 12, FontStyle.Strikeout),
            ForeColor = Color.Red
        },
    });
this.tableModel1.Rows.Add(row);
```

Do you need still the public setter on the Renderer?

**Comment by jeoffman** [comment]
Looks good, nice work.
Probably don't need the renderer to be public any more = we can always put it back when needed  :)

**Comment by schoetbi** [comment]
Any Idea why Appveyor does not get the nunit assembly via nuget?

**Pull request merged**
