### PR TITLE
Added Excel-style column filters

### PR DESCRIPTION
**Pull request by adarmus**
Columns can now have a 'Filter' button in the column header. This shows an Excel-style drop-down of all items in that column, allowing the user to untick the items they do not want displayed. This event can also be handled by custom code to allow for custom dialogs. There are 2 demo forms that show the built-in and custom behaviours.

### CODE REVIEW

**Comment by adarmus** [comment]
Do you have any thoughts on the best way to document new features? Adam

**Comment by adarmus** [comment]
The checks are only failing because of an NUnit reference

**Comment by schoetbi** [comment]
Sounds like a neat feature. I will check it out the next couple of days.

**Comment by schoetbi** [comment]
Would you mind if I extend your great work with some suggestions?

**Comment by adarmus** [comment]
Go ahead, always happy to hear what people think. Adam

**Comment by schoetbi** [comment]
I made some suggestions in branch [filters](https://github.com/schoetbi/XPTable/tree/filters) 0dce30aaf1aad82f408ef6122c3ed8bdac7ee043. But I am not able to extend this PR. Could you review my changes and then merge into adarmus/filters if you think its ok, what I did.

**Comment by adarmus** [comment]
Hi, the only change I would make is that in TextColumnFilter.UpdateFilter() the check for AnyUncheckedItems() has been removed. This optimised the case when the user ticks all the items in the dialog - as in this case there is no need to do any filtering, everything should be displayed, whereas without this check, the code will check every row even when every row will be shown.

Adam

**Comment by adarmus** [comment]
I have merged in your changes with the one thing I mentioned above. Adam

**Comment by schoetbi** [comment]
I love this feature. Thanks for this contribution!

**Pull request merged**
