### PR TITLE
#29 exception in number comparer

### PR DESCRIPTION
**Pull request by schoetbi**

### CODE REVIEW

**Review by schalpat — APPROVED** [review]
I prefer cell1/cell2 instead of lhs, rhs

**Comment by adarmus** [comment]
I also prefer cell1/cell2. Left/Right don't really apply (visually) to what the sort algorithm is doing (but its not a big deal either way).

Adam

**Review by jeoffman — APPROVED** [review]
cell1 cell2 sounds good

**Comment by schoetbi** [comment]
@adarmus : So PR ok with you? You didn't approve it.

**Review by jeoffman — COMMENTED** [review]
Was there a problem with nuget pack not getting the "author" from AssemblyInfo.cs "AssemblyCompany"?

Yeah, I am trying it now and AppVeyor doesn't appear to be pulling in the $author$ for some reason...

**Comment by schoetbi** [comment]
@jeoffman Problem with authors showed up here in Line 53 [Build](https://ci.appveyor.com/project/schoetbi/xptable/build/1.0.49#L53)

**Comment by jeoffman** [comment]
Yeah, I see the problem in AppVeyor - I swear that used to work fine so something must have changed. The change should work, but it seems like there still should be a way to get the data from AssemblyInfo.cs and then have nuget match the DLL details... I will look into it.

**Comment by adarmus** [comment]
That looks fine. Adam

**Comment by schoetbi** [comment]
@adarmus I just asked again since the review status was not approved. Thanks.

**Pull request merged**
