### PR TITLE
Run app veyor tests

### PR DESCRIPTION
**Pull request by schoetbi**
Changes: 
- Modify appveyor.yml to run NUnit-Tests
- Change of readme.txt to readme.md including the appveyor build status badge
- Update NUnit to 3.5.0

### CODE REVIEW

**Comment by adarmus** [comment]
Hi, did you mean to change the output folder to bin\Test in both Debug and Release? Adam

**Comment by schoetbi** [comment]
I like to build the unit tests in a separate directory no matter what configuration. Any other suggestion?

**Comment by adarmus** [comment]
No, no other suggestions. I just wondered if you had made the edit to test something then committed it by mistake.

**Review by jeoffman — APPROVED** [review]
Looks great, thank you for all your hard work schoetbi!

**Pull request merged**
