### PR TITLE
Added in more samples

### PR DESCRIPTION
**Pull request by adarmus**
These are samples taken from the Code Project article that show word wrap, tooltips, grouping, controls, data binding, sorting and colspan

Adam

### CODE REVIEW

**Comment by adarmus** [comment]
I've not made a pull request before - just shout if you need me to change anything. Adam

**Comment by adarmus** [comment]
Gah - looks like I shouldn't close it before you have looked at it!

**Comment by schoetbi** [comment]
I created a branch ([#12_CodeProjectSamples](https://github.com/schoetbi/XPTable/commits/%2312_CodeProjectSamples)) where I merged your branch and then changed the output folder of the sample projects to be bin\samples<config> also I removed the x86 build configuration.

If its ok to you I could merge.

**Comment by adarmus** [comment]
Sounds great. In the future would you prefer if I made a PR on a separate branch?

**Comment by schoetbi** [comment]
Would be great, since my commits would extend the PR Should I merge?

2016-07-11 13:41 GMT+02:00 adarmus notifications@github.com:

**Comment by adarmus** [comment]
Yes please

**Pull request merged**
